ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "quietModeEnabled" BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS "quietMinConfidence" TEXT NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS "quietMinSpendImpact" DOUBLE PRECISION NOT NULL DEFAULT -1,
  ADD COLUMN IF NOT EXISTS "quietNoUrgentDigestAt" TIMESTAMP(3);
